### ISSUE TITLE
Game Crashes when opening Options [Fabric] [1.9.3]

### ISSUE THREAD

**Issue by K-Brylev** [InnovativeOnlineIndustries/Emojiful#76]
Game Crashes when trying to access Options.

Modlist:
Emojiful-Fabric-1.19.3-4.1.0.jar
fabric-api-0.75.1+1.19.3.jar

Excerpt from Crashreport:

> ---- Minecraft Crash Report ----
> 
> // Daisy, daisy...
> 
> Time: 2023-03-17 19:26:44
> Description: Rendering screen
> 
> java.lang.IllegalAccessError: class eu.midnightdust.lib.util.screen.TexturedOverlayButtonWidget tried to access private field net.minecraft.class_339.field_22760 (eu.midnightdust.lib.util.screen.TexturedOverlayButtonWidget and net.minecraft.class_339 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @58134517)
	at eu.midnightdust.lib.util.screen.TexturedOverlayButtonWidget.method_25359(TexturedOverlayButtonWidget.java:35)
	at net.minecraft.class_339.method_25394(class_339.java:79)
	at net.minecraft.class_437.method_25394(class_437.java:123)
	at net.minecraft.class_429.method_25394(class_429.java:168)
	at net.minecraft.class_437.method_47413(class_437.java:113)
	at net.minecraft.class_757.method_3192(class_757.java:929)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
	at eu.midnightdust.lib.util.screen.TexturedOverlayButtonWidget.method_25359(TexturedOverlayButtonWidget.java:35)
	at net.minecraft.class_339.method_25394(class_339.java:79)
	at net.minecraft.class_437.method_25394(class_437.java:123)
	at net.minecraft.class_429.method_25394(class_429.java:168)
	at net.minecraft.class_437.method_47413(class_437.java:113)
> 
> -- Screen render details --
> Details:
	Screen name: net.minecraft.class_429
	Mouse location: Scaled: (204, 203). Absolute: (817.000000, 810.000000)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4.000000
> Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:929)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> -- Last reload --
> Details:
> 	Reload number: 1
> 	Reload reason: initial
> 	Finished: Yes
> 	Packs: vanilla, Fabric Mods
> Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2397)
	at net.minecraft.class_310.method_1514(class_310.java:800)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by KodiCraft** [comment]
Due to #74 as far as I'm aware
