### ISSUE TITLE
[1.20.1] "(...) com.hrznstudio.emojiful.platform.ForgeConfigHelper.loadCustom" is null" crash

### ISSUE THREAD

**Issue by aguzzfw** [InnovativeOnlineIndustries/Emojiful#88]
Using Emojiful 4.2.0 on 1.20.1 Forge (47.2.6)

Got a crash with the following description:

> java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.ForgeConfigSpec$BooleanValue.get()" because "com.hrznstudio.emojiful.platform.ForgeConfigHelper.loadCustom" is null
	at com.hrznstudio.emojiful.platform.ForgeConfigHelper.loadCustom(ForgeConfigHelper.java:85) ~[Emojiful-Forge-1.20.1-4.2.0.jar%23303!/:4.2.0] {re:classloading}
	at com.hrznstudio.emojiful.ClientEmojiHandler.preInitEmojis(ClientEmojiHandler.java:62) ~[Emojiful-Forge-1.20.1-4.2.0.jar%23303!/:4.2.0] {re:mixin,re:classloading}
	at com.hrznstudio.emojiful.ClientEmojiHandler.setup(ClientEmojiHandler.java:30) ~[Emojiful-Forge-1.20.1-4.2.0.jar%23303!/:4.2.0] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.handler$zki000$emojiful_initEmojis(Minecraft.java:7422) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:589) ~[client-1.20.1-20230612.114412-srg.jar%23382!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.2.6.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.6.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.6.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

Here's also the full, detailed crash log: 
[crash-2023-11-26_12.53.56-client.txt](https://github.com/InnovativeOnlineIndustries/Emojiful/files/13467354/crash-2023-11-26_12.53.56-client.txt)

**Comment by Buuz135** [comment]
Another mod is crashing on load and the blame lands on emojiful, remove emojiful and you will get another crash from another mod
